.ORIG x3000

	LEA R0, PROMPT
	PUTS
	GETC
	OUT
	AND R1, R1, #0
	ADD R1, R0, #0
	AND R0, R0, #0
	LD R2, ASCII_OFFSET
	ADD R1, R1, R2
	ST R1, ROWS
	AND R3, R3, #0
	
	MAIN_LOOP
		ADD R3, R3, #1
		LEA R0, NEWLINE
		PUTS
		AND R5, R5, #0
		ADD R6, R1, #0

		COLUMN_LOOP
			LEA R0, ASTERISK
			PUTS
			ADD R5, R5, #1
			ADD R6, R6, #-1
			BRp COLUMN_LOOP

		ADD R1, R1, #-1
	BRp MAIN_LOOP

HALT

PROMPT      .STRINGZ "\nInpur rows: "
ASTERISK    .STRINGZ "*"
NEWLINE     .STRINGZ "\n"
ASCII_OFFSET .FILL #-48
ROWS        .BLKW 1

.END